import type { ContentManifest } from "@admin/core";
import { baseFaqs, basePrices, baseServices, baseSite } from "./base.ts";

/**
 * Registr obsahu webu ponici.cz — business strana kontraktu.
 * Admin Layer tento soubor nikdy neimportuje; dostává jeho JSON
 * podobu (content/projects/ponici/manifest.json) vyexportovanou
 * přes export-manifest.ts.
 */
export const manifest: ContentManifest = {
  app: {
    name: "Ponici.cz",
    description: "Jezdecká škola pro děti i dospělé — Císařský ostrov, Praha.",
    repo: "ponici-a-cherished-journey",
  },
  locales: ["cs"],
  kinds: [
    {
      kind: "site",
      label: "Web",
      description: "Globální nastavení a texty webu.",
      idField: "slug",
      listField: "siteName",
      fields: [
        { type: "text", name: "siteName", label: "Název webu", required: true },
        { type: "url", name: "baseUrl", label: "URL webu", required: true },
        { type: "text", name: "formspreeId", label: "Formspree ID (formulář táboru)" },
        { type: "text", name: "phone", label: "Telefon (zobrazení)", required: true },
        { type: "text", name: "email", label: "E-mail", required: true },
        { type: "text", name: "locality", label: "Lokalita (např. Císařský ostrov)" },
        { type: "text", name: "address", label: "Adresa (město)" },
        { type: "text", name: "gps", label: "GPS kód" },
        { type: "text", name: "mapQuery", label: "Mapa — query (Google Maps embed)" },
        { type: "text", name: "heroKicker", label: "Hero — kicker" },
        {
          type: "image",
          name: "heroImage",
          label: "Hero — fotografie",
          help: "Velká úvodní fotografie webu.",
        },
        { type: "textarea", name: "heroTitle", label: "Hero — titulek (řádky = <br>)" },
        { type: "textarea", name: "heroSubtitle", label: "Hero — podtitulek" },
        { type: "text", name: "heroCtaPrimary", label: "Hero — hlavní tlačítko" },
        { type: "text", name: "heroCtaSecondary", label: "Hero — vedlejší tlačítko" },
        {
          type: "repeater",
          name: "heroFeatures",
          label: "Hero — vlastnosti",
          itemLabel: "Vlastnost",
          fields: [{ type: "text", name: "feature", label: "Text" }],
        },
        { type: "text", name: "aboutKicker", label: "O nás — kicker" },
        { type: "textarea", name: "aboutTitle", label: "O nás — titulek" },
        {
          type: "repeater",
          name: "aboutParagraphs",
          label: "O nás — odstavce",
          itemLabel: "Odstavec",
          fields: [{ type: "textarea", name: "paragraph", label: "Odstavec" }],
        },
        {
          type: "repeater",
          name: "stats",
          label: "O nás — čísla",
          itemLabel: "Číslo",
          fields: [
            { type: "text", name: "value", label: "Hodnota" },
            { type: "text", name: "label", label: "Popisek" },
          ],
        },
        { type: "image", name: "setkaniImage", label: "Setkání — fotografie" },
        { type: "text", name: "setkaniKicker", label: "Setkání — kicker" },
        { type: "textarea", name: "setkaniTitle", label: "Setkání — titulek" },
        { type: "textarea", name: "setkaniText", label: "Setkání — text" },
        { type: "text", name: "setkaniCta", label: "Setkání — tlačítko" },
        { type: "text", name: "programyKicker", label: "Programy — kicker" },
        { type: "textarea", name: "programyTitle", label: "Programy — titulek" },
        { type: "textarea", name: "programyIntro", label: "Programy — úvod" },
        { type: "textarea", name: "programyParagraph", label: "Programy — závěrečný odstavec" },
        { type: "image", name: "programyImage1", label: "Programy — fotografie 1 (velká)" },
        { type: "image", name: "programyImage2", label: "Programy — fotografie 2" },
        { type: "image", name: "programyImage3", label: "Programy — fotografie 3" },
        { type: "image", name: "programyImage4", label: "Programy — fotografie 4" },
        { type: "text", name: "jizdyKicker", label: "Jízdy — kicker" },
        { type: "textarea", name: "jizdyTitle", label: "Jízdy — titulek" },
        { type: "textarea", name: "jizdyIntro", label: "Jízdy — úvod" },
        { type: "textarea", name: "jizdyNote", label: "Jízdy — rozbalovací text" },
        { type: "text", name: "serviceCta", label: "Jízdy — tlačítko aktivity" },
        { type: "text", name: "vyletyKicker", label: "Výlety — kicker" },
        { type: "textarea", name: "vyletyTitle", label: "Výlety — titulek" },
        { type: "textarea", name: "vyletyIntro", label: "Výlety — úvod" },
        {
          type: "repeater",
          name: "vyletyParagraphs",
          label: "Výlety — odstavce",
          itemLabel: "Odstavec",
          fields: [{ type: "textarea", name: "paragraph", label: "Odstavec" }],
        },
        { type: "image", name: "vyletyImageMain", label: "Výlety — velká fotografie" },
        { type: "image", name: "vyletyImage1", label: "Výlety — fotografie 2" },
        { type: "image", name: "vyletyImage2", label: "Výlety — fotografie 3" },
        { type: "text", name: "stajKicker", label: "Stáj — kicker" },
        { type: "textarea", name: "stajTitle", label: "Stáj — titulek" },
        {
          type: "repeater",
          name: "stajParagraphs",
          label: "Stáj — odstavce",
          itemLabel: "Odstavec",
          fields: [{ type: "textarea", name: "paragraph", label: "Odstavec" }],
        },
        { type: "image", name: "stajImage", label: "Stáj — fotografie" },
        { type: "text", name: "oslavyKicker", label: "Oslavy — kicker" },
        { type: "textarea", name: "oslavyTitle", label: "Oslavy — titulek" },
        { type: "textarea", name: "oslavyText", label: "Oslavy — text" },
        { type: "textarea", name: "oslavyNote", label: "Oslavy — poznámka" },
        { type: "text", name: "oslavyCta", label: "Oslavy — tlačítko" },
        { type: "image", name: "oslavyImage", label: "Oslavy — fotografie" },
        { type: "text", name: "pricingKicker", label: "Ceník — kicker" },
        { type: "textarea", name: "pricingTitle", label: "Ceník — titulek" },
        { type: "textarea", name: "pricingNote", label: "Ceník — poznámka" },
        { type: "text", name: "campKicker", label: "Tábor — kicker" },
        { type: "textarea", name: "campTitle", label: "Tábor — titulek" },
        {
          type: "repeater",
          name: "campParagraphs",
          label: "Tábor — odstavce",
          itemLabel: "Odstavec",
          fields: [{ type: "textarea", name: "paragraph", label: "Odstavec" }],
        },
        { type: "text", name: "campCta", label: "Tábor — tlačítko" },
        { type: "text", name: "campFormSubject", label: "Tábor — předmět formuláře" },
        { type: "text", name: "galleryKicker", label: "Galerie — kicker" },
        { type: "textarea", name: "galleryTitle", label: "Galerie — titulek" },
        { type: "textarea", name: "galleryIntro", label: "Galerie — úvod" },
        {
          type: "repeater",
          name: "galleryImages",
          label: "Galerie — fotografie",
          itemLabel: "Fotografie",
          fields: [
            { type: "image", name: "image", label: "Fotografie" },
            { type: "text", name: "alt", label: "Popis (alt)" },
          ],
        },
        { type: "text", name: "faqKicker", label: "FAQ — kicker" },
        { type: "textarea", name: "faqTitle", label: "FAQ — titulek" },
        { type: "text", name: "contactKicker", label: "Kontakt — kicker" },
        { type: "textarea", name: "contactTitle", label: "Kontakt — titulek" },
        { type: "textarea", name: "contactText", label: "Kontakt — text" },
        { type: "textarea", name: "contactExpandable", label: "Kontakt — rozbalovací text" },
        { type: "textarea", name: "footerDescription", label: "Patička — popis" },
        { type: "text", name: "footerCopyright", label: "Patička — copyright" },
        { type: "textarea", name: "jsonLdDescription", label: "SEO — popis (JSON-LD)" },
      ],
      baseItems: baseSite,
    },
    {
      kind: "service",
      label: "Jízdy a aktivity",
      description: "Karty aktivit v sekci Jízdy a výcvik.",
      idField: "slug",
      listField: "title",
      listColumns: ["title", "layout"],
      fields: [
        { type: "text", name: "title", label: "Název", required: true },
        {
          type: "select",
          name: "icon",
          label: "Ikona",
          required: true,
          options: [
            { value: "graduation-cap", label: "Akademická čepice" },
            { value: "shield-check", label: "Štít" },
            { value: "sun", label: "Slunce" },
            { value: "trees", label: "Stromy" },
            { value: "map-pin", label: "Mapový pin" },
            { value: "party-popper", label: "Oslava" },
          ],
        },
        {
          type: "select",
          name: "layout",
          label: "Rozložení",
          required: true,
          options: [
            { value: "wide", label: "Široké (obrázek vlevo)" },
            { value: "tall", label: "Vysoké (obrázek vpravo)" },
            { value: "split", label: "Půlené" },
          ],
        },
        { type: "textarea", name: "body", label: "Popis", required: true },
        {
          type: "image",
          name: "image",
          label: "Fotografie",
          help: "URL obrázku z /images/ponici/… nebo media knihovny.",
        },
      ],
      baseItems: baseServices,
    },
    {
      kind: "price",
      label: "Ceník",
      description: "Ceníkové položky a zvýrazněný kurz.",
      idField: "slug",
      listField: "name",
      listColumns: ["name", "price", "type"],
      fields: [
        {
          type: "select",
          name: "type",
          label: "Typ",
          required: true,
          options: [
            { value: "item", label: "Položka" },
            { value: "course", label: "Zvýrazněný kurz" },
          ],
        },
        { type: "text", name: "name", label: "Název", required: true },
        { type: "text", name: "title", label: "Titulek (jen pro kurz)" },
        { type: "text", name: "price", label: "Cena (text)", required: true },
        { type: "textarea", name: "note", label: "Poznámka" },
      ],
      baseItems: basePrices,
    },
    {
      kind: "faq",
      label: "FAQ",
      description: "Často kladené otázky.",
      idField: "slug",
      listField: "question",
      listColumns: ["question"],
      fields: [
        { type: "text", name: "question", label: "Otázka", required: true },
        { type: "textarea", name: "answer", label: "Odpověď", required: true },
      ],
      baseItems: baseFaqs,
    },
  ],
};
